In [1]:
!python --version


Python 3.8.12


In [2]:
!pip show torch


Name: torch
Version: 1.10.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\admin\anaconda3\envs\py38\lib\site-packages
Requires: typing_extensions
Required-by: torchvision, torchaudio


In [3]:
!pip show numpy

Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\admin\anaconda3\envs\py38\lib\site-packages
Requires: 
Required-by: torchvision, mkl-random, mkl-fft


In [4]:
import torch

In [8]:
x = torch.empty(5,4)
x = torch.rand(5,3)
x

tensor([[0.1249, 0.0088, 0.3058],
        [0.1617, 0.8381, 0.7358],
        [0.2736, 0.0951, 0.0446],
        [0.8726, 0.5521, 0.6833],
        [0.4556, 0.2890, 0.6444]])

In [9]:
x = torch.zeros(5,3,dtype=torch.long)

In [10]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [14]:
x= torch.Tensor(5,4)

In [15]:
x

tensor([[9.0919e-39, 9.6429e-39, 9.4592e-39, 1.0561e-38],
        [9.0919e-39, 9.2755e-39, 2.9389e-39, 1.0286e-38],
        [1.0469e-38, 1.0653e-38, 1.0194e-38, 2.9389e-39],
        [1.0194e-38, 9.9184e-39, 2.9389e-39, 1.0194e-38],
        [2.9389e-39, 9.2755e-39, 9.0918e-39, 1.0010e-38]])

In [16]:
x= torch.Tensor([5.5, 3.3])

In [17]:
x

tensor([5.5000, 3.3000])

In [18]:
x= torch.ones(5,3)

In [19]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
y =torch.randn_like(x,dtype = torch.double)

In [23]:
y

tensor([[ 0.5632, -1.1967, -1.7569],
        [-0.6298, -0.6054,  1.2663],
        [ 1.9315, -0.6364, -0.1327],
        [ 0.5516,  1.7935,  0.4464],
        [ 0.3548,  0.6822,  1.5304]], dtype=torch.float64)

In [24]:
y.shape

torch.Size([5, 3])

In [26]:
y.size()

torch.Size([5, 3])

In [27]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
y = torch.rand(5,3)

In [29]:
y

tensor([[0.4509, 0.3644, 0.5136],
        [0.6777, 0.9909, 0.6185],
        [0.4720, 0.4002, 0.8225],
        [0.8635, 0.2846, 0.8514],
        [0.3793, 0.8218, 0.1989]])

In [30]:
z= x+ y
z

tensor([[1.4509, 1.3644, 1.5136],
        [1.6777, 1.9909, 1.6185],
        [1.4720, 1.4002, 1.8225],
        [1.8635, 1.2846, 1.8514],
        [1.3793, 1.8218, 1.1989]])

In [31]:
z= torch.add(x,y)
z

tensor([[1.4509, 1.3644, 1.5136],
        [1.6777, 1.9909, 1.6185],
        [1.4720, 1.4002, 1.8225],
        [1.8635, 1.2846, 1.8514],
        [1.3793, 1.8218, 1.1989]])

In [32]:
y.add_(x)
# y=y+x
y

tensor([[1.4509, 1.3644, 1.5136],
        [1.6777, 1.9909, 1.6185],
        [1.4720, 1.4002, 1.8225],
        [1.8635, 1.2846, 1.8514],
        [1.3793, 1.8218, 1.1989]])

In [33]:
a= torch.rand(4,4)
b=torch.rand(4,4)
c= torch.empty(4,4)

In [34]:
torch.add(a,b,out=c)

tensor([[1.5086, 1.4802, 1.2442, 1.6018],
        [1.3722, 0.9952, 1.6221, 1.7750],
        [1.6414, 0.6570, 1.2065, 0.8424],
        [0.7870, 1.8319, 1.5477, 1.5449]])

In [35]:
a

tensor([[0.8789, 0.5665, 0.6027, 0.6645],
        [0.8163, 0.8527, 0.8845, 0.8005],
        [0.9289, 0.3827, 0.7645, 0.0695],
        [0.7201, 0.9692, 0.6598, 0.7965]])

In [36]:
a[0:2,1]

tensor([0.5665, 0.8527])

In [37]:
a[:,1]

tensor([0.5665, 0.8527, 0.3827, 0.9692])

In [40]:
x.shape
x=torch.rand(4,4)
x.shape

torch.Size([4, 4])

In [43]:
y= x.view(16)
y.shape

torch.Size([16])

In [44]:
y=x.view(-1,8)

In [45]:
y.shape

torch.Size([2, 8])

In [46]:
x = torch.rand(1)

In [47]:
x

tensor([0.4678])

In [48]:
x.item()

0.46777087450027466

In [50]:
x = torch.rand(3,3)

In [51]:
x

tensor([[0.6182, 0.2794, 0.4163],
        [0.0949, 0.9744, 0.8253],
        [0.1027, 0.3544, 0.9840]])

In [52]:
x[0,0]

tensor(0.6182)

In [57]:
y= x[0,0]

y.item(

In [58]:
y.item()

0.6181787848472595

In [59]:
y =x.numpy()

In [60]:
y

array([[0.6181788 , 0.27939308, 0.41628408],
       [0.09486151, 0.9744328 , 0.8252549 ],
       [0.1027118 , 0.3543855 , 0.9840215 ]], dtype=float32)

In [61]:
y[0,0]

0.6181788

In [62]:
import numpy as np

In [63]:
a= np.ones(1)

In [64]:
a

array([1.])

In [66]:
b = torch.from_numpy(a)

In [67]:
b


tensor([1.], dtype=torch.float64)

In [68]:
device = torch.cuda.is_available()

In [69]:
device

False

In [70]:
x

tensor([[0.6182, 0.2794, 0.4163],
        [0.0949, 0.9744, 0.8253],
        [0.1027, 0.3544, 0.9840]])

In [71]:
 x =torch.tensor(2.0, requires_grad=True)

In [72]:
x

tensor(2., requires_grad=True)

In [73]:
y = torch.exp(x)
y
# y= e^x

tensor(7.3891, grad_fn=<ExpBackward0>)

In [74]:
y.backward()

In [75]:
y

tensor(7.3891, grad_fn=<ExpBackward0>)

In [77]:
x.grad

tensor(7.3891)

In [ ]:
torch.Tensor:
    - requires_grad: enable luu tru thong tin gradient ko
    - grad_fn : lưu thông tin hàm số đã được sử dụng của tensor 
    - backward(): hàm đạo hàm
    - grad: lưu các thông tin đạo hàm